[package]
name = "ghb"
version = "0.1.0"
authors = ["Guillaume Favelier <guillaume.favelier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
serde_json = "1.0"
termion = "1.5"
